// Package slippyclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package slippyclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyScopes = "apiKey.Scopes"
)

// AncestryEntry defines model for AncestryEntry.
type AncestryEntry struct {
	Branch        *string   `json:"branch,omitempty"`
	CommitSha     string    `json:"commit_sha"`
	CorrelationId string    `json:"correlation_id"`
	CreatedAt     time.Time `json:"created_at"`
	FailedStep    *string   `json:"failed_step,omitempty"`
	Repository    *string   `json:"repository,omitempty"`
	Status        string    `json:"status"`
}

// ComponentStepData defines model for ComponentStepData.
type ComponentStepData struct {
	Actor          *string    `json:"actor,omitempty"`
	CompletedAt    *time.Time `json:"completed_at,omitempty"`
	Component      string     `json:"component"`
	DockerfilePath *string    `json:"dockerfile_path,omitempty"`
	Error          *string    `json:"error,omitempty"`
	ImageTag       *string    `json:"image_tag,omitempty"`
	StartedAt      *time.Time `json:"started_at,omitempty"`
	Status         string     `json:"status"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`

	// Message Error message text
	Message *string `json:"message,omitempty"`

	// Value The value at the given location
	Value interface{} `json:"value,omitempty"`
}

// ErrorModel defines model for ErrorModel.
type ErrorModel struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Errors Optional list of individual error details
	Errors *[]ErrorDetail `json:"errors,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int64 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	Title *string `json:"title,omitempty"`

	// Type A URI reference to human-readable documentation for the error.
	Type *string `json:"type,omitempty"`
}

// FindAllByCommitsItem defines model for FindAllByCommitsItem.
type FindAllByCommitsItem struct {
	MatchedCommit string `json:"matched_commit"`
	Slip          Slip   `json:"slip"`
}

// FindByCommitsInputBody defines model for FindByCommitsInputBody.
type FindByCommitsInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Commits List of commit SHAs to search
	Commits *[]string `json:"commits"`

	// Repository Full repository name (owner/repo)
	Repository string `json:"repository"`
}

// FindByCommitsOutputBody defines model for FindByCommitsOutputBody.
type FindByCommitsOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema        *string `json:"$schema,omitempty"`
	MatchedCommit string  `json:"matched_commit"`
	Slip          Slip    `json:"slip"`
}

// HealthOutputBody defines model for HealthOutputBody.
type HealthOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Status Service health status
	Status string `json:"status"`
}

// Slip defines model for Slip.
type Slip struct {
	// Schema A URL to the JSON Schema for this object.
	Schema        *string                         `json:"$schema,omitempty"`
	Aggregates    map[string]*[]ComponentStepData `json:"aggregates"`
	Ancestry      *[]AncestryEntry                `json:"ancestry"`
	Branch        string                          `json:"branch"`
	CommitSha     string                          `json:"commit_sha"`
	CorrelationId string                          `json:"correlation_id"`
	CreatedAt     time.Time                       `json:"created_at"`
	PromotedTo    *string                         `json:"promoted_to,omitempty"`
	Repository    string                          `json:"repository"`
	StateHistory  *[]StateHistoryEntry            `json:"state_history"`
	Status        string                          `json:"status"`
	Steps         map[string]Step                 `json:"steps"`
	UpdatedAt     time.Time                       `json:"updated_at"`
}

// StateHistoryEntry defines model for StateHistoryEntry.
type StateHistoryEntry struct {
	Actor     string    `json:"actor"`
	Component *string   `json:"component,omitempty"`
	Message   *string   `json:"message,omitempty"`
	Status    string    `json:"status"`
	Step      string    `json:"step"`
	Timestamp time.Time `json:"timestamp"`
}

// Step defines model for Step.
type Step struct {
	Actor       *string    `json:"actor,omitempty"`
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	Error       *string    `json:"error,omitempty"`
	HeldReason  *string    `json:"held_reason,omitempty"`
	StartedAt   *time.Time `json:"started_at,omitempty"`
	Status      string     `json:"status"`
}

// FindAllByCommitsJSONRequestBody defines body for FindAllByCommits for application/json ContentType.
type FindAllByCommitsJSONRequestBody = FindByCommitsInputBody

// FindByCommitsJSONRequestBody defines body for FindByCommits for application/json ContentType.
type FindByCommitsJSONRequestBody = FindByCommitsInputBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// HealthCheck request
	HealthCheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSlipByCommit request
	GetSlipByCommit(ctx context.Context, owner string, repo string, commitSHA string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindAllByCommitsWithBody request with any body
	FindAllByCommitsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	FindAllByCommits(ctx context.Context, body FindAllByCommitsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindByCommitsWithBody request with any body
	FindByCommitsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	FindByCommits(ctx context.Context, body FindByCommitsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSlip request
	GetSlip(ctx context.Context, correlationID string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) HealthCheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthCheckRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSlipByCommit(ctx context.Context, owner string, repo string, commitSHA string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSlipByCommitRequest(c.Server, owner, repo, commitSHA)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindAllByCommitsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindAllByCommitsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindAllByCommits(ctx context.Context, body FindAllByCommitsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindAllByCommitsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindByCommitsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindByCommitsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindByCommits(ctx context.Context, body FindByCommitsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindByCommitsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSlip(ctx context.Context, correlationID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSlipRequest(c.Server, correlationID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewHealthCheckRequest generates requests for HealthCheck
func NewHealthCheckRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSlipByCommitRequest generates requests for GetSlipByCommit
func NewGetSlipByCommitRequest(server string, owner string, repo string, commitSHA string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "owner", owner, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "repo", repo, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "commitSHA", commitSHA, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/slips/by-commit/%s/%s/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFindAllByCommitsRequest calls the generic FindAllByCommits builder with application/json body
func NewFindAllByCommitsRequest(server string, body FindAllByCommitsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFindAllByCommitsRequestWithBody(server, "application/json", bodyReader)
}

// NewFindAllByCommitsRequestWithBody generates requests for FindAllByCommits with any type of body
func NewFindAllByCommitsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/slips/find-all-by-commits")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewFindByCommitsRequest calls the generic FindByCommits builder with application/json body
func NewFindByCommitsRequest(server string, body FindByCommitsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFindByCommitsRequestWithBody(server, "application/json", bodyReader)
}

// NewFindByCommitsRequestWithBody generates requests for FindByCommits with any type of body
func NewFindByCommitsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/slips/find-by-commits")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetSlipRequest generates requests for GetSlip
func NewGetSlipRequest(server string, correlationID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "correlationID", correlationID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/slips/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// HealthCheckWithResponse request
	HealthCheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthCheckResponse, error)

	// GetSlipByCommitWithResponse request
	GetSlipByCommitWithResponse(ctx context.Context, owner string, repo string, commitSHA string, reqEditors ...RequestEditorFn) (*GetSlipByCommitResponse, error)

	// FindAllByCommitsWithBodyWithResponse request with any body
	FindAllByCommitsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FindAllByCommitsResponse, error)

	FindAllByCommitsWithResponse(ctx context.Context, body FindAllByCommitsJSONRequestBody, reqEditors ...RequestEditorFn) (*FindAllByCommitsResponse, error)

	// FindByCommitsWithBodyWithResponse request with any body
	FindByCommitsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FindByCommitsResponse, error)

	FindByCommitsWithResponse(ctx context.Context, body FindByCommitsJSONRequestBody, reqEditors ...RequestEditorFn) (*FindByCommitsResponse, error)

	// GetSlipWithResponse request
	GetSlipWithResponse(ctx context.Context, correlationID string, reqEditors ...RequestEditorFn) (*GetSlipResponse, error)
}

type HealthCheckResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *HealthOutputBody
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r HealthCheckResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthCheckResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSlipByCommitResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *Slip
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r GetSlipByCommitResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSlipByCommitResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindAllByCommitsResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *[]FindAllByCommitsItem
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r FindAllByCommitsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindAllByCommitsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindByCommitsResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *FindByCommitsOutputBody
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r FindByCommitsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindByCommitsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSlipResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *Slip
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r GetSlipResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSlipResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// HealthCheckWithResponse request returning *HealthCheckResponse
func (c *ClientWithResponses) HealthCheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthCheckResponse, error) {
	rsp, err := c.HealthCheck(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthCheckResponse(rsp)
}

// GetSlipByCommitWithResponse request returning *GetSlipByCommitResponse
func (c *ClientWithResponses) GetSlipByCommitWithResponse(ctx context.Context, owner string, repo string, commitSHA string, reqEditors ...RequestEditorFn) (*GetSlipByCommitResponse, error) {
	rsp, err := c.GetSlipByCommit(ctx, owner, repo, commitSHA, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSlipByCommitResponse(rsp)
}

// FindAllByCommitsWithBodyWithResponse request with arbitrary body returning *FindAllByCommitsResponse
func (c *ClientWithResponses) FindAllByCommitsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FindAllByCommitsResponse, error) {
	rsp, err := c.FindAllByCommitsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindAllByCommitsResponse(rsp)
}

func (c *ClientWithResponses) FindAllByCommitsWithResponse(ctx context.Context, body FindAllByCommitsJSONRequestBody, reqEditors ...RequestEditorFn) (*FindAllByCommitsResponse, error) {
	rsp, err := c.FindAllByCommits(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindAllByCommitsResponse(rsp)
}

// FindByCommitsWithBodyWithResponse request with arbitrary body returning *FindByCommitsResponse
func (c *ClientWithResponses) FindByCommitsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FindByCommitsResponse, error) {
	rsp, err := c.FindByCommitsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindByCommitsResponse(rsp)
}

func (c *ClientWithResponses) FindByCommitsWithResponse(ctx context.Context, body FindByCommitsJSONRequestBody, reqEditors ...RequestEditorFn) (*FindByCommitsResponse, error) {
	rsp, err := c.FindByCommits(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindByCommitsResponse(rsp)
}

// GetSlipWithResponse request returning *GetSlipResponse
func (c *ClientWithResponses) GetSlipWithResponse(ctx context.Context, correlationID string, reqEditors ...RequestEditorFn) (*GetSlipResponse, error) {
	rsp, err := c.GetSlip(ctx, correlationID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSlipResponse(rsp)
}

// ParseHealthCheckResponse parses an HTTP response from a HealthCheckWithResponse call
func ParseHealthCheckResponse(rsp *http.Response) (*HealthCheckResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthCheckResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthOutputBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetSlipByCommitResponse parses an HTTP response from a GetSlipByCommitWithResponse call
func ParseGetSlipByCommitResponse(rsp *http.Response) (*GetSlipByCommitResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSlipByCommitResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Slip
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseFindAllByCommitsResponse parses an HTTP response from a FindAllByCommitsWithResponse call
func ParseFindAllByCommitsResponse(rsp *http.Response) (*FindAllByCommitsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindAllByCommitsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []FindAllByCommitsItem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseFindByCommitsResponse parses an HTTP response from a FindByCommitsWithResponse call
func ParseFindByCommitsResponse(rsp *http.Response) (*FindByCommitsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindByCommitsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FindByCommitsOutputBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetSlipResponse parses an HTTP response from a GetSlipWithResponse call
func ParseGetSlipResponse(rsp *http.Response) (*GetSlipResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSlipResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Slip
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}
